'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Autorun_Processor.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property autorun_processor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("autorun processor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property background_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background 6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property background_red_warn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background-red-warn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property background1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property background7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ball_green_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ball_green.hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ball_green_normal_back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ball_green.normal.back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ball_red_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ball red hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ball_red_norm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ball red norm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ball_yellow_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ball_yellow_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ball_yellow_normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ball_yellow_normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_press() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_press", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property changepass() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("changepass", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property close_red_mousedown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close_red mousedown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property close_red_mousehover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close_red mousehover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property close_red_normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close_red normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Danger() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Danger", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property form4_background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("form4_background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property green_close_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("green_close_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property green_close_normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("green_close_normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property green_close_press() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("green_close_press", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property main_window_yellow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main_window_yellow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mainnav() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mainnav", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimize_mousedown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimize_mousedown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimize_mousehover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimize_mousehover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimize_normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimize_normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property name() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("name", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property off_mouse_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("off mouse hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property off_normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("off normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property off_select() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("off-select", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property on_mouse_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("on mouse hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property on_normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("on normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property on_selected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("on selected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property scan_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scan_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property scan_hover1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scan_hover1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property scan_normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scan_normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property scan_normal1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scan_normal1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property scan_pressed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scan_pressed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property scan_pressed1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scan_pressed1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shutdown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shutdown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shutdownglow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shutdownglow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shutdownpress() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shutdownpress", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property taskmgr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("taskmgr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tool_button__click() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tool_button_ click", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tool_button_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tool_button_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tool_button_norm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tool_button_norm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
